package com.example.darnamob.Database

class PrepopulatedData {

    val prestat = arrayOf("House cleaning",
        "Water heater installation",
        "Faucet installation",
        "WC installation",
        "Heater installation",
        "Radiator installation",
        "Installation shower or bathtub",
        "Air conditioner installation",
        "Single switch installation",
        "Double switch installation",
        "Switch installation",
        "Single socket",
        "TV socket",
        "Telephone socket",
        "Internet socket",
        "Air conditioning socket",
        "Switcher",
        "Lamp",
        "Repair wall",
        "Repair and laying of tile",
        "Paint without coating",
        "Coated paint",
        "2-coat coated paint")
    val domaine = arrayOf(
        "Cleaning",
        "Plumber",
        "Plumber",
        "Plumber",
        "Plumber",
        "Plumber",
        "Plumber",
        "Plumber",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Electrician",
        "Maconier",
        "Maconier",
        "Painter",
        "Painter",
        "Painter"
    )
    val price = arrayOf(
        2000,
        2750,
        2000,
        3500,
        4500,
        7500,
        4250,
        7250,
        900,
        1300,
        850,
        700,
        700,
        1200,
        700,
        1250,
        1600,
        700,
        7000,
        3000,
        250,
        400,
        500
    )
    val duration = arrayOf(
        2,
        2,
        1,
        2,
        1,
        1,
        2,
        2,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        4,
        4,
        1,
        1,
        1
    )
    val materials = arrayOf(
        "Vacuum cleaner - Chemicals and cleaning products - Brush - Scrubber-dryer",
        " Water heaters",
        "Faucet",
        "WC",
        "Heater",
        "Radiator",
        "Shower or bathtub",
        "Air conditioner",
        "single switch",
        "double switch",
        "switch",
        "single socket",
        "TV socket",
        "telephone socket",
        "internet socket",
        "air conditioning socket",
        "Switcher",
        "Lampe",
        "Peinture - Mastic",
        "tile",
        "paint",
        "paint",
        "paint"
    )

    val emailAdmins = arrayOf(
        "ms_sidahmed@esi.dz",
        "ms_kadid@esi.dz"
    )
    val password = arrayOf(
        "1234",
        "1234"
    )

}